import { GeoPage, JsonLd } from '../../../components/geo-page';
import { breadcrumbJsonLd, publicMetadata } from '../../../lib/seo';

export const metadata = publicMetadata('/comparar/exacta7-vs-vin', 'Exacta7 vs VIN', 'Comparativa factual de Exacta7 y Veterinary Information Network: comunidad, referencia clínica, AEMPS, cálculo y contexto de uso.');

export default function Page() {
  return <><JsonLd value={breadcrumbJsonLd([{ name: 'Inicio', path: '/' }, { name: 'Comparar', path: '/comparar' }, { name: 'Exacta7 vs VIN', path: '/comparar/exacta7-vs-vin' }])}/><GeoPage eyebrow="COMPARATIVA FACTUAL" title="Exacta7 vs VIN" lead="VIN y Exacta7 cubren necesidades diferentes. VIN se presenta como una comunidad y base de conocimiento veterinaria global; Exacta7 se orienta a datos regulatorios españoles, cálculo transparente y trazabilidad." sections={[
    { title: 'Alcance documentado', paragraphs: ['VIN describe una red internacional para veterinarios, estudiantes y académicos con búsqueda, recursos clínicos, comunidad, formación y herramientas. Sus páginas oficiales describen contenidos revisados por especialistas y recursos de prescripción.', 'Exacta7 no es una comunidad clínica ni una biblioteca de tratamientos. Mantiene separado el dato regulatorio AEMPS/CIMA Vet de cualquier evidencia clínica publicada tras revisión humana.'] },
    { title: 'Cómo difieren', table: { headers: ['Dimensión', 'VIN', 'Exacta7'], rows: [['Ámbito', 'Comunidad y recursos veterinarios internacionales', 'Herramienta web centrada en el contexto regulatorio español'], ['Datos AEMPS/CIMA Vet', 'No se afirma como fuente', 'Sí, catálogo regulatorio publicado'], ['Comunidad y consulta entre colegas', 'Sí, según VIN', 'No'], ['Recursos clínicos y formación', 'Sí, según VIN', 'No se publica contenido clínico sin revisión humana'], ['Cálculo transparente', 'VIN informa de calculadoras y recursos', 'Fórmula, unidades y pasos visibles para operaciones publicadas'], ['Selección automática de dosis', 'No se evalúa aquí', 'No']] } },
    { title: 'Qué elegir según el caso', items: ['VIN puede ser pertinente si se busca comunidad profesional, formación o su base de conocimiento global.', 'CIMA Vet/AEMPS sigue siendo la fuente oficial para información regulatoria en España.', 'Exacta7 puede ser pertinente para consultar el catálogo regulatorio publicado, mantener un contexto local temporal y revisar cálculos matemáticos paso a paso.'] },
    { title: 'Fuente externa', paragraphs: ['Los atributos de VIN proceden de sus páginas oficiales About VIN y Veterinary Information Network, consultadas el 2026-09-21.'], links: [{ href: 'https://www.vin.com/vin/about-vin', label: 'VIN: About VIN' }, { href: 'https://www.vin.com/vin/', label: 'VIN: página principal' }] },
  ]} links={[{ href: '/para/veterinarios', label: 'Exacta7 para veterinarios' }, { href: '/fuentes', label: 'Fuentes y límites' }]} /></>;
}
