export type CalculatorId = 'dose' | 'cri' | 'fluidos' | 'unit-converter' | 'dilutions' | 'drip-rate' | 'rer' | 'bsa' | 'osmolarity' | 'anion-gap' | 'water-deficit' | 'transfusion';
export type CalculatorPlan = 'free' | 'pro';
export type CalculatorReviewState = 'published' | 'review_required' | 'draft';
export type CalculatorLocale = 'es' | 'en' | 'fr';

export type CalculatorMetadata = {
  id: CalculatorId;
  slug: CalculatorId;
  category: 'dose' | 'infusion' | 'fluid' | 'conversion' | 'dilution' | 'nutrition' | 'physiology' | 'transfusion';
  plan: CalculatorPlan;
  requiresActivePatient: boolean;
  acceptsAempsPresentation: boolean;
  supportedUnits: readonly string[];
  inputs: readonly string[];
  mathSource: { title: string; url: string; version: string };
  version: string;
  reviewedAt: string;
  reviewState: CalculatorReviewState;
  warnings: readonly string[];
  name: Record<CalculatorLocale, string>;
  description: Record<CalculatorLocale, string>;
};

const dimensionalAnalysis = { title: 'NIST · International System of Units', url: 'https://www.nist.gov/pml/owm/metric-si/si-units', version: 'SI reference' } as const;

export const calculatorRegistry: readonly CalculatorMetadata[] = [
  { id: 'dose', slug: 'dose', category: 'dose', plan: 'free', requiresActivePatient: true, acceptsAempsPresentation: true, supportedUnits: ['mg/kg', 'µg/kg', 'mg/mL', 'µg/mL'], inputs: ['weight', 'dose', 'concentration'], mathSource: dimensionalAnalysis, version: '0.1.0', reviewedAt: '2026-09-16', reviewState: 'published', warnings: ['The professional selects indication, route, dose and concentration.'], name: { es: 'Dosis y volumen', en: 'Dose and volume', fr: 'Dose et volume' }, description: { es: 'Convierte una dosis seleccionada en cantidad y volumen.', en: 'Converts a selected dose into amount and volume.', fr: 'Convertit une dose choisie en quantité et volume.' } },
  { id: 'cri', slug: 'cri', category: 'infusion', plan: 'free', requiresActivePatient: true, acceptsAempsPresentation: true, supportedUnits: ['mg/kg/h', 'µg/kg/min', 'mg/mL', 'µg/mL'], inputs: ['weight', 'rate', 'concentration'], mathSource: dimensionalAnalysis, version: '0.1.0', reviewedAt: '2026-09-16', reviewState: 'published', warnings: ['The professional selects rate, concentration and pump settings.'], name: { es: 'Infusión continua · CRI', en: 'Continuous infusion · CRI', fr: 'Perfusion continue · CRI' }, description: { es: 'Convierte una tasa seleccionada en caudal matemático.', en: 'Converts a selected rate into mathematical flow.', fr: 'Convertit un débit choisi en débit mathématique.' } },
  { id: 'fluidos', slug: 'fluidos', category: 'fluid', plan: 'free', requiresActivePatient: true, acceptsAempsPresentation: false, supportedUnits: ['mL/kg/h'], inputs: ['weight', 'rate'], mathSource: dimensionalAnalysis, version: '0.1.0', reviewedAt: '2026-09-16', reviewState: 'published', warnings: ['The professional selects fluid rate and clinical objective.'], name: { es: 'Fluidoterapia básica', en: 'Basic fluid therapy', fr: 'Fluidothérapie de base' }, description: { es: 'Convierte una tasa seleccionada de mL/kg/h a mL/h.', en: 'Converts a selected mL/kg/h rate to mL/h.', fr: 'Convertit un débit choisi de mL/kg/h en mL/h.' } },
  { id: 'unit-converter', slug: 'unit-converter', category: 'conversion', plan: 'free', requiresActivePatient: false, acceptsAempsPresentation: false, supportedUnits: ['mg', 'g', 'µg', 'mL', 'L', 'kg'], inputs: ['value', 'fromUnit', 'toUnit'], mathSource: dimensionalAnalysis, version: '0.1.0', reviewedAt: '2026-09-20', reviewState: 'published', warnings: ['Only compatible dimensions can be converted.'], name: { es: 'Conversor de unidades', en: 'Unit converter', fr: 'Convertisseur d’unités' }, description: { es: 'Conversión dimensional sin decisión clínica.', en: 'Dimensional conversion without clinical decision-making.', fr: 'Conversion dimensionnelle sans décision clinique.' } },
  { id: 'dilutions', slug: 'dilutions', category: 'dilution', plan: 'pro', requiresActivePatient: false, acceptsAempsPresentation: true, supportedUnits: ['mg/mL', 'mL'], inputs: ['sourceConcentration', 'targetConcentration', 'finalVolume'], mathSource: dimensionalAnalysis, version: '0.1.0', reviewedAt: '2026-09-20', reviewState: 'published', warnings: ['The professional verifies compatibility, diluent and final preparation.'], name: { es: 'Diluciones', en: 'Dilutions', fr: 'Dilutions' }, description: { es: 'Resuelve C₁V₁ = C₂V₂ con datos introducidos.', en: 'Solves C₁V₁ = C₂V₂ from entered values.', fr: 'Résout C₁V₁ = C₂V₂ à partir des valeurs saisies.' } },
  { id: 'drip-rate', slug: 'drip-rate', category: 'infusion', plan: 'pro', requiresActivePatient: false, acceptsAempsPresentation: false, supportedUnits: ['mL/h', 'drops/mL', 'drops/min'], inputs: ['flow', 'dropFactor'], mathSource: dimensionalAnalysis, version: '0.1.0', reviewedAt: '2026-09-20', reviewState: 'published', warnings: ['Verify the administration set drop factor physically.'], name: { es: 'Velocidad de goteo', en: 'Drip rate', fr: 'Débit de goutte-à-goutte' }, description: { es: 'Convierte caudal y factor de goteo en gotas/min.', en: 'Converts flow and drop factor into drops/min.', fr: 'Convertit le débit et le facteur de goutte en gouttes/min.' } },
  { id: 'rer', slug: 'rer', category: 'nutrition', plan: 'pro', requiresActivePatient: true, acceptsAempsPresentation: false, supportedUnits: ['kcal/day'], inputs: ['weight', 'species', 'formula'], mathSource: { title: 'Veterinary formula review required', url: 'https://exacta7.com/fuentes', version: 'pending' }, version: '0.1.0', reviewedAt: '', reviewState: 'review_required', warnings: ['Not published: formula and limits need veterinary review.'], name: { es: 'Requerimiento energético', en: 'Resting energy requirement', fr: 'Besoin énergétique de repos' }, description: { es: 'Pendiente de validación veterinaria.', en: 'Pending veterinary validation.', fr: 'En attente de validation vétérinaire.' } },
  { id: 'bsa', slug: 'bsa', category: 'physiology', plan: 'pro', requiresActivePatient: true, acceptsAempsPresentation: false, supportedUnits: ['m²'], inputs: ['weight', 'species', 'formula'], mathSource: { title: 'Veterinary formula review required', url: 'https://exacta7.com/fuentes', version: 'pending' }, version: '0.1.0', reviewedAt: '', reviewState: 'review_required', warnings: ['Not published: species-specific formula needs veterinary review.'], name: { es: 'Superficie corporal', en: 'Body surface area', fr: 'Surface corporelle' }, description: { es: 'Pendiente de validación veterinaria.', en: 'Pending veterinary validation.', fr: 'En attente de validation vétérinaire.' } },
  { id: 'osmolarity', slug: 'osmolarity', category: 'physiology', plan: 'pro', requiresActivePatient: false, acceptsAempsPresentation: false, supportedUnits: ['mOsm/L'], inputs: ['laboratoryValues', 'formula'], mathSource: { title: 'Laboratory formula review required', url: 'https://exacta7.com/fuentes', version: 'pending' }, version: '0.1.0', reviewedAt: '', reviewState: 'review_required', warnings: ['Not published: formula depends on validated laboratory context.'], name: { es: 'Osmolaridad / osmolalidad', en: 'Osmolarity / osmolality', fr: 'Osmolarité / osmolalité' }, description: { es: 'Pendiente de validación veterinaria.', en: 'Pending veterinary validation.', fr: 'En attente de validation vétérinaire.' } },
  { id: 'anion-gap', slug: 'anion-gap', category: 'physiology', plan: 'pro', requiresActivePatient: false, acceptsAempsPresentation: false, supportedUnits: ['mmol/L'], inputs: ['laboratoryValues', 'formula'], mathSource: { title: 'Laboratory formula review required', url: 'https://exacta7.com/fuentes', version: 'pending' }, version: '0.1.0', reviewedAt: '', reviewState: 'review_required', warnings: ['Not published: laboratory and species context need review.'], name: { es: 'Anion gap', en: 'Anion gap', fr: 'Trou anionique' }, description: { es: 'Pendiente de validación veterinaria.', en: 'Pending veterinary validation.', fr: 'En attente de validation vétérinaire.' } },
  { id: 'water-deficit', slug: 'water-deficit', category: 'fluid', plan: 'pro', requiresActivePatient: true, acceptsAempsPresentation: false, supportedUnits: ['mL'], inputs: ['weight', 'dehydration', 'correctionPeriod'], mathSource: { title: 'Veterinary fluid formula review required', url: 'https://exacta7.com/fuentes', version: 'pending' }, version: '0.1.0', reviewedAt: '', reviewState: 'review_required', warnings: ['Not published: requires veterinary validation.'], name: { es: 'Déficit hídrico', en: 'Water deficit', fr: 'Déficit hydrique' }, description: { es: 'Pendiente de validación veterinaria.', en: 'Pending veterinary validation.', fr: 'En attente de validation vétérinaire.' } },
  { id: 'transfusion', slug: 'transfusion', category: 'transfusion', plan: 'pro', requiresActivePatient: true, acceptsAempsPresentation: false, supportedUnits: ['mL'], inputs: ['weight', 'haematocrit', 'target', 'donor', 'formula'], mathSource: { title: 'Veterinary transfusion formula review required', url: 'https://exacta7.com/fuentes', version: 'pending' }, version: '0.1.0', reviewedAt: '', reviewState: 'review_required', warnings: ['Not published: formula and transfusion workflow need veterinary review.'], name: { es: 'Transfusión', en: 'Transfusion', fr: 'Transfusion' }, description: { es: 'Pendiente de validación veterinaria.', en: 'Pending veterinary validation.', fr: 'En attente de validation vétérinaire.' } },
] as const;

export const publishedCalculators = calculatorRegistry.filter(calculator => calculator.reviewState === 'published');
export function findCalculator(slug: string) { return calculatorRegistry.find(calculator => calculator.slug === slug); }
