import { GeoPage, JsonLd } from '../../../components/geo-page';
import { breadcrumbJsonLd, publicMetadata } from '../../../lib/seo';

export const metadata = publicMetadata('/comparar/exacta7-vs-cima-vet', 'Exacta7 vs CIMA Vet', 'Diferencias entre Exacta7 y CIMA Vet/AEMPS: información regulatoria oficial, consulta estructurada, cálculo transparente y límites.');

export default function Page() {
  return <><JsonLd value={breadcrumbJsonLd([{ name: 'Inicio', path: '/' }, { name: 'Comparar', path: '/comparar' }, { name: 'Exacta7 vs CIMA Vet', path: '/comparar/exacta7-vs-cima-vet' }])}/><GeoPage eyebrow="COMPARATIVA FACTUAL" title="Exacta7 vs CIMA Vet" lead="CIMA Vet/AEMPS es la fuente oficial de información regulatoria. Exacta7 no sustituye esa condición: ofrece una capa de consulta, contexto y cálculo transparente sobre datos regulatorios publicados." sections={[
    { title: 'Qué es cada herramienta', paragraphs: ['CIMA Vet es el Centro de Información online de Medicamentos Veterinarios de la AEMPS. La AEMPS indica que ofrece información sobre medicamentos veterinarios autorizados y sus fichas técnicas, prospectos y estado administrativo.', 'Exacta7 es una herramienta web de apoyo a la decisión clínica veterinaria. Separa datos regulatorios, evidencia clínica revisada y cálculo matemático.'] },
    { title: 'Diferencias relevantes', table: { headers: ['Dimensión', 'CIMA Vet/AEMPS', 'Exacta7'], rows: [['Condición de fuente oficial', 'Sí: fuente regulatoria AEMPS', 'No; enlaza y publica datos regulatorios aprobados'], ['Medicamentos autorizados en España', 'Consulta oficial', 'Catálogo regulatorio publicado desde AEMPS/CIMA Vet'], ['Ficha técnica y prospecto', 'Disponibles desde la fuente oficial', 'Enlaces a los documentos oficiales'], ['Contexto local de paciente', 'No se afirma en esta comparación', 'Caso temporal local para cálculos'], ['Calculadoras con fórmula visible', 'No se afirma en esta comparación', 'Sí, con valores elegidos por el profesional'], ['Selección automática de dosis', 'No se evalúa aquí', 'No'], ['Fuentes y trazabilidad', 'Información regulatoria oficial', 'Fuentes, versión y límites visibles']] } },
    { title: 'Cuándo consultar cada una', items: ['Consulta CIMA Vet/AEMPS para información regulatoria oficial, ficha técnica, prospecto, estado administrativo, alertas y actualizaciones.', 'Exacta7 puede resultar útil para relacionar una consulta regulatoria con el contexto temporal de un paciente y realizar operaciones matemáticas transparentes con valores seleccionados por el profesional.', 'Ante cualquier decisión de prescripción o tratamiento, corresponde al profesional verificar la fuente oficial y aplicar su juicio clínico.'] },
    { title: 'Fuentes', paragraphs: ['La AEMPS presenta CIMA Vet como su Centro de Información online de Medicamentos Veterinarios. Exacta7 usa el Nomenclátor CIMA Vet con corte 2026-09-16 y no convierte sus datos en recomendaciones clínicas.'], links: [{ href: '/fuentes/actualizaciones-aemps', label: 'Ver actualización AEMPS publicada' }, { href: '/fuentes', label: 'Ver metodología de Exacta7' }] },
  ]} links={[{ href: '/medicamentos', label: 'Explorar medicamentos AEMPS' }, { href: '/calculadoras', label: 'Abrir calculadoras' }]} /></>;
}
