'use client';

import { useI18n } from './i18n';

export type ReceiptData = { calculationId: string; createdAt: string; calculator: string; patient?: string; inputs: readonly [string, string][]; result: string; formula: string; steps: string; source: string; version: string; presentation?: string; concentration?: string; warnings: readonly string[]; savedLocally?: boolean };

export function CalculationReceipt({ data }: { data: ReceiptData }) {
  const { locale } = useI18n();
  const t = locale === 'en' ? { title: 'CALCULATION RECORD', date: 'Date and time', patient: 'Patient', inputs: 'Inputs', presentation: 'Presentation', formula: 'Formula', conversions: 'Conversions', source: 'Source', warnings: 'Warnings', copy: 'Copy', print: 'Print', copied: 'Copied', local: 'Saved locally for this case', note: 'This is a record of a mathematical calculation, not an administration instruction.' } : locale === 'fr' ? { title: 'REGISTRE DU CALCUL', date: 'Date et heure', patient: 'Patient', inputs: 'Données saisies', presentation: 'Présentation', formula: 'Formule', conversions: 'Conversions', source: 'Source', warnings: 'Avertissements', copy: 'Copier', print: 'Imprimer', copied: 'Copié', local: 'Enregistré localement pour ce cas', note: 'Il s’agit d’un registre de calcul mathématique, pas d’une instruction d’administration.' } : { title: 'REGISTRO DEL CÁLCULO', date: 'Fecha y hora', patient: 'Paciente', inputs: 'Datos introducidos', presentation: 'Presentación', formula: 'Fórmula', conversions: 'Conversiones', source: 'Fuente', warnings: 'Advertencias', copy: 'Copiar', print: 'Imprimir', copied: 'Copiado', local: 'Guardado localmente para este caso', note: 'Es un registro de cálculo matemático, no una instrucción de administración.' };
  const text = `${t.title}\n${data.calculator}\n${t.date}: ${new Date(data.createdAt).toLocaleString(locale)}\nID: ${data.calculationId}\n${data.patient ? `${t.patient}: ${data.patient}\n` : ''}${t.inputs}:\n${data.inputs.map(([key, value]) => `- ${key}: ${value}`).join('\n')}\n${data.presentation ? `${t.presentation}: ${data.presentation}\n` : ''}${data.concentration ? `${data.concentration}\n` : ''}${t.formula}: ${data.formula}\n${t.conversions}: ${data.steps}\n${t.source}: ${data.source}\n${t.warnings}: ${data.warnings.join(' ')}\n${t.note}`;
  async function copy() { await navigator.clipboard?.writeText(text); const element = document.querySelector<HTMLButtonElement>(`[data-receipt-copy="${data.calculationId}"]`); if (element) { const old = element.textContent; element.textContent = t.copied; window.setTimeout(() => { element.textContent = old; }, 1800); } }
  return <details className="calculation-receipt"><summary>{t.title}</summary><dl><div><dt>ID</dt><dd>{data.calculationId}</dd></div><div><dt>{t.date}</dt><dd>{new Date(data.createdAt).toLocaleString(locale)}</dd></div>{data.patient && <div><dt>{t.patient}</dt><dd>{data.patient}</dd></div>}</dl><h3>{t.inputs}</h3><ul>{data.inputs.map(([key,value]) => <li key={key}><strong>{key}:</strong> {value}</li>)}</ul>{data.presentation && <p><strong>{t.presentation}:</strong> {data.presentation}</p>}{data.concentration && <p><strong>{data.concentration}</strong></p>}<p><strong>{t.formula}:</strong> {data.formula}</p><p><strong>{t.conversions}:</strong> {data.steps}</p><p><strong>{t.source}:</strong> {data.source}</p><p><strong>{t.warnings}:</strong> {data.warnings.join(' ')}</p>{data.savedLocally && <p className="small-text">{t.local}</p>}<p className="small-text">{t.note}</p><div className="receipt-actions"><button type="button" data-receipt-copy={data.calculationId} onClick={() => void copy()}>{t.copy}</button><button type="button" onClick={() => window.print()}>{t.print}</button></div></details>;
}
