'use client';

import { useI18n } from './i18n';

const privacy = {
  es: { eyebrow: 'PRIVACIDAD', title: 'Política de privacidad', lead: 'Exacta7 trata únicamente los datos necesarios para responder consultas y mantener el servicio.', contact: 'Contacto', contactText: 'Los datos enviados mediante el formulario se usan para responder a la consulta. La base del tratamiento es tu consentimiento. No los cedemos con fines comerciales y se conservan durante el tiempo necesario para atender y documentar la comunicación.', clinical: 'Datos clínicos', clinicalText: 'No envíes datos identificativos de pacientes ni información clínica confidencial. Exacta7 no necesita esos datos para atender consultas generales o técnicas.', analytics: 'Analítica', analyticsText: 'Google Analytics solo se activa tras tu consentimiento. La implementación excluye textos de búsqueda, datos de pacientes, pesos, dosis, concentraciones, indicaciones y resultados de cálculos.', rights: 'Derechos', rightsText: 'Puedes solicitar acceso, rectificación o supresión escribiendo a', google: 'cómo usa Google la información de sitios que utilizan sus servicios' },
  en: { eyebrow: 'PRIVACY', title: 'Privacy policy', lead: 'Exacta7 processes only the data needed to respond to enquiries and maintain the service.', contact: 'Contact', contactText: 'Data sent through the form are used to respond to your enquiry. Processing is based on your consent. We do not share them for commercial purposes and retain them only as long as needed to handle and document the communication.', clinical: 'Clinical data', clinicalText: 'Do not send patient-identifying data or confidential clinical information. Exacta7 does not need these data to answer general or technical enquiries.', analytics: 'Analytics', analyticsText: 'Google Analytics activates only after your consent. The implementation excludes search text, patient data, weights, doses, concentrations, indications, and calculation results.', rights: 'Your rights', rightsText: 'You can request access, rectification, or erasure by writing to', google: 'how Google uses information from sites that use its services' },
  fr: { eyebrow: 'CONFIDENTIALITÉ', title: 'Politique de confidentialité', lead: 'Exacta7 traite uniquement les données nécessaires pour répondre aux demandes et assurer le service.', contact: 'Contact', contactText: 'Les données envoyées par le formulaire servent à répondre à votre demande. Le traitement repose sur votre consentement. Elles ne sont pas cédées à des fins commerciales et sont conservées uniquement le temps nécessaire au suivi et à la documentation de la communication.', clinical: 'Données cliniques', clinicalText: 'N’envoyez pas de données permettant d’identifier des patients ni d’informations cliniques confidentielles. Exacta7 n’en a pas besoin pour répondre aux demandes générales ou techniques.', analytics: 'Analytique', analyticsText: 'Google Analytics s’active uniquement après votre consentement. La mise en œuvre exclut les textes de recherche, données de patients, poids, doses, concentrations, indications et résultats de calculs.', rights: 'Vos droits', rightsText: 'Vous pouvez demander l’accès, la rectification ou l’effacement en écrivant à', google: 'la manière dont Google utilise les informations issues des sites qui utilisent ses services' },
} as const;

const cookies = {
  es: { eyebrow: 'COOKIES', title: 'Política de cookies', lead: 'Exacta7 usa almacenamiento técnico y, con tu permiso, medición agregada.', necessary: 'Almacenamiento necesario', necessaryText: 'Guardamos tus preferencias de idioma y consentimiento en el navegador. También se conserva localmente el contexto de paciente que tú introduces para facilitar el uso; no se envía a Google Analytics.', ga: 'Google Analytics 4', gaText: 'Si aceptas la analítica, GA4 mide páginas visitadas y acciones generales. La medición está denegada por defecto mediante Consent Mode v2 y no incluye textos de búsqueda ni parámetros clínicos.', choice: 'Cambiar la elección', choiceText: 'Puedes borrar el almacenamiento y las cookies de exacta7.com desde la configuración del navegador para volver a mostrar el selector de consentimiento.' },
  en: { eyebrow: 'COOKIES', title: 'Cookie policy', lead: 'Exacta7 uses technical storage and, with your permission, aggregated measurement.', necessary: 'Necessary storage', necessaryText: 'We store your language and consent preferences in your browser. The patient context you enter is also saved locally to make the service easier to use; it is not sent to Google Analytics.', ga: 'Google Analytics 4', gaText: 'If you accept analytics, GA4 measures visited pages and general actions. Measurement is denied by default through Consent Mode v2 and does not include search text or clinical parameters.', choice: 'Change your choice', choiceText: 'You can clear exacta7.com storage and cookies in your browser settings to show the consent selector again.' },
  fr: { eyebrow: 'COOKIES', title: 'Politique relative aux cookies', lead: 'Exacta7 utilise un stockage technique et, avec votre accord, une mesure agrégée.', necessary: 'Stockage nécessaire', necessaryText: 'Nous conservons vos préférences de langue et de consentement dans votre navigateur. Le contexte du patient que vous saisissez est aussi enregistré localement pour faciliter l’utilisation ; il n’est pas transmis à Google Analytics.', ga: 'Google Analytics 4', gaText: 'Si vous acceptez l’analytique, GA4 mesure les pages consultées et les actions générales. La mesure est refusée par défaut via Consent Mode v2 et n’inclut ni textes de recherche ni paramètres cliniques.', choice: 'Modifier votre choix', choiceText: 'Vous pouvez supprimer le stockage et les cookies de exacta7.com dans les réglages du navigateur pour afficher à nouveau le sélecteur de consentement.' },
} as const;

export function PrivacyContent() {
  const { locale } = useI18n(); const copy = privacy[locale];
  return <article className="page-intro legal-page"><p className="eyebrow">{copy.eyebrow}</p><h1>{copy.title}</h1><p className="lead">{copy.lead}</p><h2>{copy.contact}</h2><p>{copy.contactText}</p><h2>{copy.clinical}</h2><p>{copy.clinicalText}</p><h2>{copy.analytics}</h2><p>{copy.analyticsText} <a href="https://policies.google.com/technologies/partner-sites" target="_blank" rel="noreferrer">{copy.google}</a>.</p><h2>{copy.rights}</h2><p>{copy.rightsText} <a href="mailto:info@exacta7.com">info@exacta7.com</a>.</p></article>;
}

export function CookiesContent() {
  const { locale } = useI18n(); const copy = cookies[locale];
  return <article className="page-intro legal-page"><p className="eyebrow">{copy.eyebrow}</p><h1>{copy.title}</h1><p className="lead">{copy.lead}</p><h2>{copy.necessary}</h2><p>{copy.necessaryText}</p><h2>{copy.ga}</h2><p>{copy.gaText}</p><h2>{copy.choice}</h2><p>{copy.choiceText}</p></article>;
}
