'use client';

import Link from 'next/link';
import { useI18n } from './i18n';
import { usePatient, type LocalFavorite } from './patient-context';

export function FavoriteButton({ favorite }: { favorite: Omit<LocalFavorite, 'created_at'> }) { const { store, addFavorite, removeFavorite } = usePatient(); const saved = store.favorites.some(item => item.id === favorite.id); const { locale } = useI18n(); const label = locale === 'en' ? saved ? 'Remove from favourites' : 'Save as favourite' : locale === 'fr' ? saved ? 'Retirer des favoris' : 'Ajouter aux favoris' : saved ? 'Quitar de favoritos' : 'Guardar favorito'; return <button type="button" className="text-button" onClick={() => saved ? removeFavorite(favorite.id) : addFavorite(favorite)}>{saved ? '★' : '☆'} {label}</button>; }

export function LocalHistory() { const { store, removeCalculation, clearCalculations, removeFavorite } = usePatient(); const { locale } = useI18n(); const t = locale === 'en' ? { eye: 'LOCAL WORKSPACE', title: 'Calculation history', lead: 'Only stored on this device. Deleting a case also removes its calculations.', none: 'No local calculation records yet.', review: 'Review', duplicate: 'Duplicate', remove: 'Delete', clear: 'Clear history', saved: 'Saved', favorites: 'Favourites', noFavorites: 'No favourites saved on this device.' } : locale === 'fr' ? { eye: 'ESPACE LOCAL', title: 'Historique des calculs', lead: 'Conservé uniquement sur cet appareil. Supprimer un cas supprime aussi ses calculs.', none: 'Aucun registre de calcul local pour le moment.', review: 'Réviser', duplicate: 'Dupliquer', remove: 'Supprimer', clear: 'Effacer l’historique', saved: 'Enregistré', favorites: 'Favoris', noFavorites: 'Aucun favori enregistré sur cet appareil.' } : { eye: 'ESPACIO LOCAL', title: 'Historial de cálculos', lead: 'Se conserva solo en este dispositivo. Al eliminar un caso se eliminan también sus cálculos.', none: 'Todavía no hay registros de cálculo locales.', review: 'Revisar', duplicate: 'Duplicar', remove: 'Eliminar', clear: 'Limpiar historial', saved: 'Guardado', favorites: 'Favoritos', noFavorites: 'No hay favoritos guardados en este dispositivo.' };
  const calculations = store.cases.flatMap(record => record.calculations.map(calculation => ({ ...calculation, caseName: record.case.alias ?? record.case.case_id.slice(0, 4), species: record.case.species, weight: record.case.weight }))).sort((a,b) => b.created_at.localeCompare(a.created_at));
  return <><section className="page-intro compact"><p className="eyebrow green">{t.eye}</p><h1>{t.title}</h1><p className="lead">{t.lead}</p></section><section className="local-list"><div className="section-heading"><h2>{t.title}</h2>{calculations.length > 0 && <button type="button" className="danger-button" onClick={clearCalculations}>{t.clear}</button>}</div>{calculations.length ? calculations.map(item => <article className="panel local-record" key={item.calculation_id}><h3>{item.tool_type}</h3><p>{item.caseName} · {item.species} · {item.weight} kg</p><small>{t.saved}: {new Date(item.created_at).toLocaleString(locale)} · {item.calculation_id}</small><div><Link href={`/calculadoras/${item.tool_type}`}>{t.review}</Link><Link href={`/calculadoras/${item.tool_type}`}>{t.duplicate}</Link><button type="button" onClick={() => removeCalculation(item.calculation_id)}>{t.remove}</button></div></article>) : <p className="empty-block">{t.none}</p>}</section><section className="local-list"><h2>{t.favorites}</h2>{store.favorites.length ? store.favorites.map(item => <article className="local-record" key={item.id}><Link href={item.href}>{item.label}</Link><button type="button" onClick={() => removeFavorite(item.id)} aria-label={t.remove}>×</button></article>) : <p className="empty-block">{t.noFavorites}</p>}</section></>;
}
