'use client';
import Link from 'next/link';
import type{RegulatoryProduct,RegulatoryRelease}from'@exacta7/knowledge/regulatory';
import{useI18n,type Locale}from'./i18n';
const labels={
es:{crumb:'Vademécum',reg:'FICHA REGULATORIA AEMPS',shell:'FICHA DE MEDICAMENTO',data:'DATOS DEL MEDICAMENTO',presentations:'PRESENTACIONES',recommendations:'RECOMENDACIONES PUBLICADAS',calculators:'CALCULADORAS RELACIONADAS',sources:'FUENTES',status:'Estado registral',authorized:'Autorizado',market:'Comercialización',yes:'Sí',no:'No',regNo:'Número de registro',active:'Principios activos',species:'Especies de destino',routes:'Vías',prescription:'Requiere receta',exclusive:'Administración exclusiva veterinaria',controlled:'Administración bajo control veterinario',first:'Primera autorización',atc:'ATCvet',code:'Código nacional',nonePresentations:'No hay presentaciones AEMPS revisadas disponibles para esta ficha.',noneRecommendations:'No hay recomendaciones clínicas publicadas para este medicamento. Los datos regulatorios no establecen una dosis clínica.',calculatorText:'Introduce la indicación, vía, dosis y concentración seleccionadas por el profesional.',openCalculator:'Abrir calculadora',technical:'Ficha técnica',leaflet:'Prospecto',openData:'Datos abiertos AEMPS',sourceDate:'Fecha de los datos fuente',approval:'Publicación regulatoria aprobada',shellText:'Esta ficha de navegación todavía no contiene un producto regulatorio ni una recomendación clínica publicada.'},
en:{crumb:'Formulary',reg:'AEMPS REGULATORY RECORD',shell:'MEDICINE RECORD',data:'MEDICINE DATA',presentations:'PRESENTATIONS',recommendations:'PUBLISHED RECOMMENDATIONS',calculators:'RELATED CALCULATORS',sources:'SOURCES',status:'Registration status',authorized:'Authorised',market:'Marketing',yes:'Yes',no:'No',regNo:'Registration number',active:'Active ingredients',species:'Target species',routes:'Routes',prescription:'Prescription required',exclusive:'Veterinary exclusive administration',controlled:'Administration under veterinary control',first:'First authorisation',atc:'ATCvet',code:'National code',nonePresentations:'No reviewed AEMPS presentations are available for this record.',noneRecommendations:'No clinical recommendations have been published for this medicine. Regulatory data do not define a clinical dose.',calculatorText:'Enter the indication, route, dose and concentration selected by the professional.',openCalculator:'Open calculator',technical:'Technical sheet',leaflet:'Package leaflet',openData:'AEMPS open data',sourceDate:'Source data date',approval:'Regulatory publication approved',shellText:'This navigation record has no published regulatory product or clinical recommendation yet.'},
fr:{crumb:'Formulaire',reg:'FICHE RÉGLEMENTAIRE AEMPS',shell:'FICHE MÉDICAMENT',data:'DONNÉES DU MÉDICAMENT',presentations:'PRÉSENTATIONS',recommendations:'RECOMMANDATIONS PUBLIÉES',calculators:'CALCULATEURS ASSOCIÉS',sources:'SOURCES',status:'Statut d’enregistrement',authorized:'Autorisé',market:'Commercialisation',yes:'Oui',no:'Non',regNo:'Numéro d’enregistrement',active:'Principes actifs',species:'Espèces cibles',routes:'Voies',prescription:'Prescription obligatoire',exclusive:'Administration vétérinaire exclusive',controlled:'Administration sous contrôle vétérinaire',first:'Première autorisation',atc:'ATCvet',code:'Code national',nonePresentations:'Aucune présentation AEMPS révisée n’est disponible pour cette fiche.',noneRecommendations:'Aucune recommandation clinique n’a été publiée pour ce médicament. Les données réglementaires ne définissent pas une dose clinique.',calculatorText:'Saisissez l’indication, la voie, la dose et la concentration choisies par le professionnel.',openCalculator:'Ouvrir le calculateur',technical:'Résumé des caractéristiques',leaflet:'Notice',openData:'Données ouvertes AEMPS',sourceDate:'Date des données source',approval:'Publication réglementaire approuvée',shellText:'Cette fiche de navigation ne contient encore aucun produit réglementaire ni recommandation clinique publié.'}
}satisfies Record<Locale,Record<string,string>>;
export function MedicineDetail({product,shellName,release}:{product:RegulatoryProduct|null;shellName?:string;release:RegulatoryRelease['release']}){const{locale}=useI18n();const t=labels[locale];const name=product?.name??shellName??'';return <><div className="breadcrumb"><Link href="/medicamentos">{t.crumb}</Link><span>/</span>{name}</div><div className="drug-title"><div><p className="eyebrow green">{product?t.reg:t.shell}</p><h1>{name}</h1>{product&&<p>{product.activeSubstances.join(' · ')}</p>}</div>{product&&<span className="tag">{t.authorized}</span>}</div><nav className="anchor-nav"><a href="#datos">1. {t.data}</a><a href="#presentaciones">2. {t.presentations}</a><a href="#recomendaciones">3. {t.recommendations}</a><a href="#calculadoras">4. {t.calculators}</a><a href="#fuentes">5. {t.sources}</a></nav><article className="monograph">
<section id="datos"><span className="section-number">01</span><div><h2>{t.data}</h2>{!product?<div className="empty-block">{t.shellText}</div>:<dl className="regulatory-grid"><div><dt>{t.status}</dt><dd>{t.authorized}</dd></div><div><dt>{t.market}</dt><dd>{product.marketingStatus==='SI'?t.yes:t.no}</dd></div><div><dt>{t.regNo}</dt><dd>{product.registrationNumber}</dd></div><div><dt>{t.first}</dt><dd>{product.firstAuthorizationDate}</dd></div><div><dt>{t.active}</dt><dd>{product.ingredients.map(item=>`${item.name} ${item.amount} ${item.unit}`).join(' · ')}</dd></div><div><dt>{t.species}</dt><dd>{product.species.join(', ')}</dd></div><div><dt>{t.routes}</dt><dd>{product.routes.join(', ')}</dd></div><div><dt>{t.atc}</dt><dd>{product.atcvet.join(', ')}</dd></div><div><dt>{t.prescription}</dt><dd>{product.prescriptionRequired==='SI'?t.yes:t.no}</dd></div><div><dt>{t.exclusive}</dt><dd>{product.veterinaryExclusiveAdministration==='SI'?t.yes:t.no}</dd></div><div><dt>{t.controlled}</dt><dd>{product.veterinarianControlAdministration==='SI'?t.yes:t.no}</dd></div></dl>}</div></section>
<section id="presentaciones"><span className="section-number">02</span><div><h2>{t.presentations}</h2>{product?.presentations.length?product.presentations.map(item=><article className="panel" key={`${item.nationalCode}-${item.label}`}><h3>{item.label}</h3><p>{t.code}: <strong>{item.nationalCode}</strong>{item.packageContent&&<> · {item.packageContent} {item.packageContentUnit}</>}</p></article>):<div className="empty-block">{t.nonePresentations}</div>}</div></section>
<section id="recomendaciones"><span className="section-number">03</span><div><h2>{t.recommendations}</h2><div className="empty-block">{t.noneRecommendations}</div></div></section>
<section id="calculadoras"><span className="section-number">04</span><div><h2>{t.calculators}</h2><p>{t.calculatorText}</p><Link className="primary" href="/calculadoras/dose">{t.openCalculator} →</Link></div></section>
<section id="fuentes"><span className="section-number">05</span><div><h2>{t.sources}</h2>{product&&<p><a href={product.technicalSheetUrl} target="_blank" rel="noreferrer">{t.technical} ↗</a> · <a href={product.leafletUrl} target="_blank" rel="noreferrer">{t.leaflet} ↗</a></p>}<p><a href="https://sede.aemps.gob.es/datos-abiertos/" target="_blank" rel="noreferrer">{t.openData} ↗</a></p><small>{t.sourceDate}: {release.sourceDataDate} · {t.approval}: {release.approvedAt}</small></div></section>
</article></>}
