'use client';
import Link from 'next/link';
import { useMemo, useState } from 'react';
import { normalize } from '@exacta7/knowledge';
import { ClinicalSearch } from './search';
import { useI18n, type Locale } from './i18n';
type Product={slug:string;name:string;registrationNumber:string;activeSubstances:string[];species:string[];routes:string[];marketingStatus:string};
type Release={sourceDataDate:string;approvedAt:string;counts:{publishedProducts:number;publishedPresentations:number;excludedUnresolvedProducts:number}};
const labels={
  es:{crumb:'Inicio',eyebrow:'CONSULTA REGULATORIA',title:'Vademécum veterinario',lead:'Busca productos veterinarios oficiales, principios activos, especies y vías.',filter:'Filtrar el directorio',placeholder:'Nombre, principio activo o número de registro',showing:'Mostrando',of:'de',records:'productos',marketed:'Comercializado',notMarketed:'No comercializado',previous:'Anterior',next:'Siguiente',source:'Corte de la fuente oficial',approved:'publicación regulatoria aprobada',authorized:'productos AEMPS autorizados y',presentations:'presentaciones. Solo datos regulatorios; sin recomendaciones clínicas de dosis.'},
  en:{crumb:'Home',eyebrow:'REGULATORY CONSULTATION',title:'Veterinary formulary',lead:'Search official veterinary products, active ingredients, species and routes.',filter:'Filter the directory',placeholder:'Name, active ingredient or registration number',showing:'Showing',of:'of',records:'products',marketed:'Marketed',notMarketed:'Not marketed',previous:'Previous',next:'Next',source:'Official source snapshot',approved:'regulatory publication approved',authorized:'authorised AEMPS products and',presentations:'presentations. Regulatory data only; no clinical dose recommendations.'},
  fr:{crumb:'Accueil',eyebrow:'CONSULTATION RÉGLEMENTAIRE',title:'Formulaire vétérinaire',lead:'Recherchez les produits vétérinaires officiels, principes actifs, espèces et voies.',filter:'Filtrer le répertoire',placeholder:'Nom, principe actif ou numéro d’enregistrement',showing:'Affichage',of:'sur',records:'produits',marketed:'Commercialisé',notMarketed:'Non commercialisé',previous:'Précédent',next:'Suivant',source:'Instantané de la source officielle',approved:'publication réglementaire approuvée',authorized:'produits AEMPS autorisés et',presentations:'présentations. Données réglementaires uniquement, sans recommandation de dose clinique.'},
} satisfies Record<Locale,Record<string,string>>;
export function MedicineDirectory({products,release}:{products:Product[];release:Release}){
  const{locale}=useI18n();const t=labels[locale];const[filter,setFilter]=useState('');const[page,setPage]=useState(1);const pageSize=40;
  const filtered=useMemo(()=>{const q=normalize(filter);if(!q)return products;const tokens=q.split(' ');return products.filter(p=>{const hay=normalize([p.name,p.registrationNumber,...p.activeSubstances,...p.species,...p.routes].join(' '));return tokens.every(token=>hay.includes(token));});},[filter,products]);
  const pages=Math.max(1,Math.ceil(filtered.length/pageSize));const safePage=Math.min(page,pages);const visible=filtered.slice((safePage-1)*pageSize,safePage*pageSize);
  return <><div className="breadcrumb"><Link href="/">{t.crumb}</Link><span>/</span>{t.title}</div><div className="page-intro compact"><p className="eyebrow green">{t.eyebrow}</p><h1>{t.title}</h1><p className="lead">{t.lead}</p></div><div className="notice"><strong>{release.counts.publishedProducts.toLocaleString(locale)} {t.authorized} {release.counts.publishedPresentations.toLocaleString(locale)} {t.presentations}</strong><br/>{t.source}: {release.sourceDataDate} · {t.approved}: {release.approvedAt}.</div><section className="search-panel"><ClinicalSearch medicationOnly/></section><section className="tool-section"><div className="directory-filter"><label>{t.filter}<input type="search" value={filter} onChange={event=>{setFilter(event.target.value);setPage(1);}} placeholder={t.placeholder}/></label><p className="muted">{t.showing} {visible.length} {t.of} {filtered.length.toLocaleString(locale)} {t.records}</p></div>{visible.map(product=><Link className="directory-row" key={product.slug} href={`/medicamentos/${product.slug}`}><span><strong>{product.name}</strong><small>{product.activeSubstances.join(' · ')}</small></span><span className="muted">{product.registrationNumber}</span><span className="tag">{product.marketingStatus==='SI'?t.marketed:t.notMarketed}</span><span aria-hidden>→</span></Link>)}<div className="pagination"><button type="button" disabled={safePage<=1} onClick={()=>setPage(value=>Math.max(1,value-1))}>{t.previous}</button><span>{safePage} / {pages}</span><button type="button" disabled={safePage>=pages} onClick={()=>setPage(value=>Math.min(pages,value+1))}>{t.next}</button></div></section></>;
}
