'use client';

import Link from 'next/link';
import { CheckoutButton } from './checkout-button';
import { useI18n } from './i18n';

export function Pricing() {
  const { locale } = useI18n();
  const t = locale === 'en' ? { eyebrow:'PLANS', title:'Clear clinical tools for every stage of your practice.', lead:'Start free with clinical search and the AEMPS formulary. Move to Pro when you need greater continuity and advanced access.', section:'Choose the level of support you need', free:'Exacta7 Free', pro:'Exacta7 Pro', freeLead:'For discovering Exacta7 and organising your account.', proLead:'For professionals who use Exacta7 regularly.', freeItems:['Free account','Clinical search and public AEMPS formulary','Core calculation tools','Source and methodology access'], proItems:['Everything in Free','Extended calculation and account history','Published clinical recommendation access','Priority product updates and support'], freeCta:'Create free account', monthly:'per month', yearly:'per year', annualNote:'€8.25/month, billed annually'} : locale === 'fr' ? { eyebrow:'FORMULES', title:'Des outils cliniques clairs à chaque étape de votre pratique.', lead:'Commencez gratuitement avec la recherche clinique et le formulaire AEMPS. Passez à Pro pour davantage de continuité et d’accès avancé.', section:'Choisissez le niveau d’accompagnement dont vous avez besoin', free:'Exacta7 Free', pro:'Exacta7 Pro', freeLead:'Pour découvrir Exacta7 et organiser votre compte.', proLead:'Pour les professionnels qui utilisent Exacta7 régulièrement.', freeItems:['Compte gratuit','Recherche clinique et formulaire AEMPS public','Outils de calcul essentiels','Accès aux sources et à la méthodologie'], proItems:['Tout ce qui est inclus dans Free','Calculs étendus et historique du compte','Accès aux recommandations cliniques publiées','Mises à jour et assistance prioritaires'], freeCta:'Créer un compte gratuit', monthly:'par mois', yearly:'par an', annualNote:'8,25 €/mois, facturés annuellement'} : { eyebrow:'PLANES', title:'Herramientas clínicas claras para cada etapa de tu práctica.', lead:'Empieza gratis con el buscador clínico y el vademécum AEMPS. Pasa a Pro cuando necesites más continuidad y acceso avanzado.', section:'Elige el nivel de apoyo que necesitas', free:'Exacta7 Free', pro:'Exacta7 Pro', freeLead:'Para descubrir Exacta7 y organizar tu cuenta.', proLead:'Para profesionales que utilizan Exacta7 de forma habitual.', freeItems:['Cuenta gratuita','Buscador clínico y vademécum AEMPS público','Herramientas de cálculo esenciales','Acceso a fuentes y metodología'], proItems:['Todo lo incluido en Free','Cálculos ampliados e historial de cuenta','Acceso a recomendaciones clínicas publicadas','Actualizaciones y soporte prioritarios'], freeCta:'Crear cuenta gratis', monthly:'al mes', yearly:'al año', annualNote:'8,25 €/mes, facturado anualmente'};
  return <><section className="page-intro plans-intro"><p className="eyebrow green">{t.eyebrow}</p><h1>{t.title}</h1><p className="lead">{t.lead}</p></section><section className="pricing-section" aria-labelledby="pricing-title"><h2 id="pricing-title">{t.section}</h2><div className="pricing-grid"><article className="pricing-card"><img src="/brand/price-free.png" alt="" width="116" height="116"/><p className="eyebrow">FREE</p><h3>{t.free}</h3><p>{t.freeLead}</p><strong className="price">0 € <small>{t.monthly}</small></strong><ul>{t.freeItems.map(item => <li key={item}>{item}</li>)}</ul><Link className="primary" href="/acceso?next=/cuenta">{t.freeCta} <span aria-hidden>→</span></Link></article><article className="pricing-card pricing-card-pro"><img src="/brand/price-pro-monthly.png" alt="" width="116" height="116"/><p className="eyebrow">PRO · MENSUAL</p><h3>{t.pro}</h3><p>{t.proLead}</p><strong className="price">9,90 € <small>{t.monthly}</small></strong><ul>{t.proItems.map(item => <li key={item}>{item}</li>)}</ul><CheckoutButton interval="monthly"/></article><article className="pricing-card pricing-card-yearly"><img src="/brand/price-pro-yearly.png" alt="" width="116" height="116"/><p className="eyebrow">PRO · ANUAL</p><h3>{t.pro}</h3><p>{t.proLead}</p><strong className="price">99 € <small>{t.yearly}</small></strong><p className="annual-saving">{t.annualNote}</p><ul>{t.proItems.map(item => <li key={item}>{item}</li>)}</ul><CheckoutButton interval="yearly"/></article></div><p className="pricing-note">Los precios de prueba no generan cobros reales. Las decisiones clínicas siguen correspondiendo al profesional.</p></section></>;
}
