'use client';

import Image from 'next/image';
import Link from 'next/link';
import { useState } from 'react';
import { CheckoutButton } from './checkout-button';
import { useI18n } from './i18n';
import { getProPrice, pricingConfig } from '../lib/pricing-config';

const labels = {
  es: {
    eyebrow: 'PLANES', title: 'Herramientas clínicas claras para cada etapa de tu práctica.', lead: 'Empieza gratis con el buscador clínico y el vademécum AEMPS. Pasa a Pro cuando necesites más continuidad y acceso avanzado.', section: 'Elige el nivel de apoyo que necesitas', free: 'Exacta7 Gratis', pro: 'Exacta7 Pro', freeLead: 'Para descubrir Exacta7 y organizar tu cuenta.', proLead: 'Para profesionales que utilizan Exacta7 de forma habitual.', freeItems: ['Cuenta gratuita', 'Buscador clínico y vademécum AEMPS público', 'Herramientas de cálculo esenciales', 'Acceso a fuentes y metodología'], proItems: ['Todo lo incluido en Gratis', 'Herramientas Pro: diluciones y goteo', 'Registros de cálculo transparentes', 'Actualizaciones y soporte prioritarios'], freeCta: 'Crear cuenta gratis', monthlyPlan: 'PRO · MENSUAL', annualPlan: 'PRO · ANUAL', annualNote: 'Facturado anualmente', monthlyOption: 'Mensual', annualOption: 'Anual', billingFrequency: 'Frecuencia de facturación', testNote: 'Los precios de prueba no generan cobros reales. Las decisiones clínicas siguen correspondiendo al profesional.', compareTitle: 'Compara antes de elegir', compareLead: 'Gratis cubre la consulta y los cálculos esenciales. Pro añade continuidad para el trabajo clínico frecuente.', feature: 'Función', freePlan: 'Gratis', proPlan: 'Pro', comparison: [['Consulta de medicamentos AEMPS', 'Sí', 'Sí'], ['Calculadoras esenciales', 'Sí', 'Sí'], ['Diluciones y goteo', '—', 'Sí'], ['Registros de cálculo', '—', 'Sí'], ['Soporte prioritario', '—', 'Sí']], linksTitle: 'Explora Exacta7 antes de decidir', calculators: 'Ver calculadoras', formulary: 'Consultar vademécum AEMPS', sources: 'Revisar fuentes y metodología', faqTitle: 'Preguntas frecuentes sobre Exacta7 Pro', faq: [['¿Puedo empezar gratis?', 'Sí. Exacta7 Gratis incluye una cuenta, el buscador clínico, el vademécum AEMPS público y las herramientas de cálculo esenciales.'], ['¿Qué añade Exacta7 Pro?', 'Pro incluye las herramientas de diluciones y goteo, registros de cálculo transparentes y soporte prioritario.'], ['¿Cuál es la diferencia entre el plan mensual y el anual?', 'Ambos incluyen las mismas funciones Pro. El mensual cuesta {monthly}. El anual se factura una vez al año por {yearly}, {equivalent}, con un {saving}.'], ['¿Los cobros son reales?', 'No durante esta fase: el checkout usa Stripe en modo de prueba y los precios de prueba no generan cargos reales.']], logos: { free: '/brand/price-free.png', monthly: '/brand/price-pro-monthly.png', yearly: '/brand/price-pro-yearly.png' },
  },
  en: {
    eyebrow: 'PLANS', title: 'Clear clinical tools for every stage of your practice.', lead: 'Start free with clinical search and the AEMPS formulary. Move to Pro when you need greater continuity and advanced access.', section: 'Choose the level of support you need', free: 'Exacta7 Free', pro: 'Exacta7 Pro', freeLead: 'For discovering Exacta7 and organising your account.', proLead: 'For professionals who use Exacta7 regularly.', freeItems: ['Free account', 'Clinical search and public AEMPS formulary', 'Core calculation tools', 'Source and methodology access'], proItems: ['Everything in Free', 'Pro tools: dilutions and drip rate', 'Transparent calculation records', 'Priority product updates and support'], freeCta: 'Create free account', monthlyPlan: 'PRO · MONTHLY', annualPlan: 'PRO · ANNUAL', annualNote: 'Billed annually', monthlyOption: 'Monthly', annualOption: 'Annual', billingFrequency: 'Billing frequency', testNote: 'Test prices do not create real charges. Clinical decisions remain the professional’s responsibility.', compareTitle: 'Compare before choosing', compareLead: 'Free covers consultation and core calculations. Pro adds continuity for frequent clinical work.', feature: 'Feature', freePlan: 'Free', proPlan: 'Pro', comparison: [['AEMPS medicine consultation', 'Yes', 'Yes'], ['Core calculation tools', 'Yes', 'Yes'], ['Dilutions and drip rate', '—', 'Yes'], ['Calculation records', '—', 'Yes'], ['Priority support', '—', 'Yes']], linksTitle: 'Explore Exacta7 before deciding', calculators: 'View calculators', formulary: 'Browse the AEMPS formulary', sources: 'Review sources and methodology', faqTitle: 'Exacta7 Pro frequently asked questions', faq: [['Can I start for free?', 'Yes. Exacta7 Free includes an account, clinical search, the public AEMPS formulary, and core calculation tools.'], ['What does Exacta7 Pro add?', 'Pro includes dilution and drip-rate tools, transparent calculation records, and priority support.'], ['What is the difference between monthly and annual?', 'Both include the same Pro features. Monthly costs {monthly}. Annual is billed once a year at {yearly}, {equivalent}, saving {saving}.'], ['Are the charges real?', 'Not in this phase: checkout uses Stripe in test mode, and test prices do not create real charges.']], logos: { free: '/brand/price-free-en.png', monthly: '/brand/price-pro-monthly-en.png', yearly: '/brand/price-pro-yearly-en.png' },
  },
  fr: {
    eyebrow: 'FORMULES', title: 'Des outils cliniques clairs à chaque étape de votre pratique.', lead: 'Commencez gratuitement avec la recherche clinique et le formulaire AEMPS. Passez à Pro pour davantage de continuité et d’accès avancé.', section: 'Choisissez le niveau d’accompagnement dont vous avez besoin', free: 'Exacta7 Gratuit', pro: 'Exacta7 Pro', freeLead: 'Pour découvrir Exacta7 et organiser votre compte.', proLead: 'Pour les professionnels qui utilisent Exacta7 régulièrement.', freeItems: ['Compte gratuit', 'Recherche clinique et formulaire AEMPS public', 'Outils de calcul essentiels', 'Accès aux sources et à la méthodologie'], proItems: ['Tout ce qui est inclus dans Gratuit', 'Outils Pro : dilutions et goutte-à-goutte', 'Registres de calcul transparents', 'Mises à jour et assistance prioritaires'], freeCta: 'Créer un compte gratuit', monthlyPlan: 'PRO · MENSUEL', annualPlan: 'PRO · ANNUEL', annualNote: 'Facturé annuellement', monthlyOption: 'Mensuel', annualOption: 'Annuel', billingFrequency: 'Fréquence de facturation', testNote: 'Les tarifs de test ne génèrent aucun débit réel. Les décisions cliniques relèvent du professionnel.', compareTitle: 'Comparez avant de choisir', compareLead: 'Gratuit couvre la consultation et les calculs essentiels. Pro apporte de la continuité pour le travail clinique fréquent.', feature: 'Fonction', freePlan: 'Gratuit', proPlan: 'Pro', comparison: [['Consultation des médicaments AEMPS', 'Oui', 'Oui'], ['Outils de calcul essentiels', 'Oui', 'Oui'], ['Dilutions et goutte-à-goutte', '—', 'Oui'], ['Registres de calcul', '—', 'Oui'], ['Assistance prioritaire', '—', 'Oui']], linksTitle: 'Découvrez Exacta7 avant de choisir', calculators: 'Voir les calculateurs', formulary: 'Consulter le formulaire AEMPS', sources: 'Voir les sources et la méthodologie', faqTitle: 'Questions fréquentes sur Exacta7 Pro', faq: [['Puis-je commencer gratuitement ?', 'Oui. Exacta7 Gratuit inclut un compte, la recherche clinique, le formulaire AEMPS public et les outils de calcul essentiels.'], ['Qu’ajoute Exacta7 Pro ?', 'Pro inclut les outils de dilution et de goutte-à-goutte, des registres de calcul transparents et une assistance prioritaire.'], ['Quelle est la différence entre le mensuel et l’annuel ?', 'Les deux incluent les mêmes fonctions Pro. Le mensuel coûte {monthly}. L’annuel est facturé une fois par an à {yearly}, {equivalent}, avec une économie de {saving}.'], ['Les débits sont-ils réels ?', 'Pas pendant cette phase : le checkout utilise Stripe en mode test et les tarifs de test ne génèrent aucun débit réel.']], logos: { free: '/brand/price-free-fr.png', monthly: '/brand/price-pro-monthly-fr.png', yearly: '/brand/price-pro-yearly-fr.png' },
  },
} as const;

export function Pricing() {
  const { locale } = useI18n();
  const t = labels[locale];
  const [annual, setAnnual] = useState(false);
  const interval = annual ? pricingConfig.intervals.yearly : pricingConfig.intervals.monthly;
  const replacePriceTokens = (text: string) => text.replace('{monthly}', pricingConfig.pro.monthly.display[locale]).replace('{yearly}', pricingConfig.pro.yearly.display[locale]).replace('{equivalent}', pricingConfig.pro.yearly.equivalent[locale]).replace('{saving}', pricingConfig.pro.yearly.saving[locale]);

  return <>
    <section className="page-intro plans-intro"><p className="eyebrow green">{t.eyebrow}</p><h1>{t.title}</h1><p className="lead">{t.lead}</p></section>
    <section className="pricing-section" aria-labelledby="pricing-title">
      <h2 id="pricing-title">{t.section}</h2>
      <div className="pricing-grid">
        <article className="pricing-card"><Image src={t.logos.free} alt={`${t.free} logo`} width={116} height={116}/><p className="eyebrow">{t.free}</p><h3>{t.free}</h3><p>{t.freeLead}</p><strong className="price">{pricingConfig.free.display[locale]}</strong><ul>{t.freeItems.map(item => <li key={item}>{item}</li>)}</ul><Link className="primary" href="/acceso?next=/cuenta">{t.freeCta} <span aria-hidden>→</span></Link></article>
        <article className={`pricing-card pricing-card-pro${annual ? ' pricing-card-yearly' : ''}`}><div className="billing-toggle" role="group" aria-label={t.billingFrequency}><button type="button" className={!annual ? 'is-selected' : ''} aria-pressed={!annual} onClick={() => setAnnual(false)}>{t.monthlyOption}</button><button type="button" className={annual ? 'is-selected' : ''} aria-pressed={annual} onClick={() => setAnnual(true)}>{t.annualOption}</button></div><Image src={annual ? t.logos.yearly : t.logos.monthly} alt={`${t.pro} ${annual ? t.annualPlan : t.monthlyPlan} logo`} width={116} height={116}/><p className="eyebrow">{annual ? t.annualPlan : t.monthlyPlan}</p><h3>{t.pro}</h3><p>{t.proLead}</p><strong className="price">{getProPrice(interval, locale)}</strong>{annual && <p className="annual-saving">{t.annualNote}. {pricingConfig.pro.yearly.equivalent[locale]}. {pricingConfig.pro.yearly.saving[locale]}.</p>}<ul>{t.proItems.map(item => <li key={item}>{item}</li>)}</ul><CheckoutButton interval={interval}/></article>
      </div>
      <p className="pricing-note">{t.testNote}</p>
    </section>
    <section className="plans-detail" aria-labelledby="comparison-title"><h2 id="comparison-title">{t.compareTitle}</h2><p className="lead">{t.compareLead}</p><div className="plans-comparison" role="region" aria-label={t.compareTitle}><table><thead><tr><th scope="col">{t.feature}</th><th scope="col">{t.freePlan}</th><th scope="col">{t.proPlan}</th></tr></thead><tbody>{t.comparison.map(([feature, free, pro]) => <tr key={feature}><th scope="row">{feature}</th><td>{free}</td><td>{pro}</td></tr>)}</tbody></table></div></section>
    <section className="plans-detail" aria-labelledby="explore-title"><h2 id="explore-title">{t.linksTitle}</h2><nav className="plans-links" aria-label={t.linksTitle}><Link href="/calculadoras">{t.calculators} →</Link><Link href="/medicamentos">{t.formulary} →</Link><Link href="/fuentes">{t.sources} →</Link></nav></section>
    <section className="plans-detail plans-faq" aria-labelledby="faq-title"><h2 id="faq-title">{t.faqTitle}</h2>{t.faq.map(([question, answer]) => <details key={question}><summary>{question}</summary><p>{replacePriceTokens(answer)}</p></details>)}</section>
  </>;
}
