import { GeoPage, JsonLd } from '../../../components/geo-page';
import { breadcrumbJsonLd, publicMetadata } from '../../../lib/seo';

export const metadata = publicMetadata('/comparar/exacta7-vs-plumbs', 'Exacta7 vs Plumb’s', 'Comparativa factual de Exacta7 y Plumb’s: alcance, regulación española, referencia clínica, cálculo y fuentes.');

export default function Page() {
  return <><JsonLd value={breadcrumbJsonLd([{ name: 'Inicio', path: '/' }, { name: 'Comparar', path: '/comparar' }, { name: 'Exacta7 vs Plumb’s', path: '/comparar/exacta7-vs-plumbs' }])}/><GeoPage eyebrow="COMPARATIVA FACTUAL" title="Exacta7 vs Plumb’s" lead="Ambas son herramientas veterinarias, pero su alcance es distinto: Exacta7 se centra en la consulta regulatoria española, contexto y cálculo transparente; Plumb’s se presenta como una referencia farmacológica veterinaria." sections={[
    { title: 'Alcance documentado', paragraphs: ['Plumb’s describe su producto como una referencia de fármacos veterinarios con monografías, actualizaciones continuas, calculadora de conversión, notas y herramientas de interacción. Sus contenidos y precios se consultan en su sitio oficial.', 'Exacta7 publica datos regulatorios AEMPS/CIMA Vet de España y operaciones deterministas. No publica monografías clínicas generadas automáticamente ni selecciona pautas.'] },
    { title: 'Cómo difieren', table: { headers: ['Dimensión', 'Plumb’s', 'Exacta7'], rows: [['Enfoque declarado', 'Referencia farmacológica veterinaria', 'Apoyo a la decisión con datos regulatorios, cálculo y fuentes'], ['Datos regulatorios de España', 'No se afirma como fuente AEMPS', 'Catálogo aprobado desde AEMPS/CIMA Vet'], ['Monografías farmacológicas', 'Sí, según su sitio oficial', 'No se generan ni publican sin revisión humana'], ['Calculadoras', 'Incluye una calculadora de conversión, según su sitio', 'Calculadoras de unidades, dosis/volumen, CRI, fluidos, diluciones y goteo publicadas según revisión'], ['Selección automática de medicamentos o dosis', 'No se evalúa aquí', 'No'], ['Precio público', 'Consultar su precio oficial', 'Gratis, 7,99 €/mes o 59,99 €/año en modo de prueba actual']] } },
    { title: 'Qué elegir según el caso', items: ['Para verificar información regulatoria española, la referencia es CIMA Vet/AEMPS.', 'Para una referencia farmacológica clínica, consulta el alcance y las condiciones de Plumb’s directamente con su proveedor.', 'Para un flujo de consulta AEMPS, paciente temporal y fórmula matemática visible, Exacta7 puede ser útil dentro de sus límites.'] },
    { title: 'Fuente externa', paragraphs: ['Los atributos de Plumb’s se basan en sus páginas oficiales de funciones y precios, consultadas el 2026-09-21. No se reproduce su contenido clínico.'], links: [{ href: 'https://plumbs.com/features/drug-monographs/', label: 'Plumb’s: Drug Monographs' }, { href: 'https://plumbs.com/pricing/', label: 'Plumb’s: Pricing' }] },
  ]} links={[{ href: '/alternativas/plumbs', label: 'Cómo valorar alternativas a Plumb’s' }, { href: '/fuentes', label: 'Fuentes de Exacta7' }]} /></>;
}
